---

- name: Install argus_extra_packages
  pkgng:
    name: "{{ argus_extra_packages }}"
    state: present

- name: Install argus_package
  pkgng:
    name: "{{ argus_package }}"
    state: present

- name: Enable argus_service
  service:
    name: "{{ argus_service }}"
    enabled: yes

- name: "Create /etc/rc.conf.d/{{ argus_service }}"
  template:
    src: FreeBSD.rcd.j2
    dest: "/etc/rc.conf.d/{{ argus_service }}"
    mode: 0644
    validate: sh -n %s
  notify:
    - Restart argus_service

- name: Create argus_group
  # XXX the package does not create user and group
  group:
    name: "{{ argus_group }}"

- name: Create argus_user
  user:
    comment: "User {{ argus_user }}"
    create_home: no
    group: "{{ argus_group }}"
    groups: "{{ argus_extra_groups }}"
    name: "{{ argus_user }}"
    state: present
