---

- name: Install argus_extra_packages
  apt:
    name: "{{ argus_extra_packages }}"
    state: present

- name: Install argus_package
  apt:
    name: "{{ argus_package }}"
    state: present

- name: Edit /lib/systemd/system/ssh.service (EnvironmentFile)
  # XXX the unit file does not support /etc/default/argus
  ini_file:
    path: /lib/systemd/system/argus.service
    section: Service
    option: EnvironmentFile
    value: "-/etc/default/argus"
    no_extra_spaces: yes
  notify:
    - Restart argus_service
    - Reload systemd

- name: Edit /lib/systemd/system/argus.service (ExecStart)
  # XXX the unit file does not support /etc/default/argus
  ini_file:
    path: /lib/systemd/system/argus.service
    section: Service
    option: ExecStart
    value: "/usr/sbin/argus $ARGUS_OPTIONS"
    no_extra_spaces: yes
  notify:
    - Restart argus_service
    - Reload systemd

- name: Enable argus_service
  service:
    name: "{{ argus_service }}"
    enabled: yes

- name: "Create /etc/default/{{ argus_service }}"
  template:
    src: Debian.default.j2
    dest: "/etc/default/{{ argus_service }}"
    mode: 0644
    # keep the original copy in case you need the defaults in it
    backup: yes
    validate: sh -n %s
  notify:
    - Restart argus_service

- name: Create argus_group
  # XXX the package does not create user and group
  group:
    name: "{{ argus_group }}"

- name: Create argus_user
  user:
    comment: "User {{ argus_user }}"
    create_home: no
    group: "{{ argus_group }}"
    groups: "{{ argus_extra_groups }}"
    name: "{{ argus_user }}"
    state: present
